camera0: /dev/video0
camera1: /dev/video2
frame_width: 640
frame_height: 480
checkerboard_rows: 9
checkerboard_columns: 6
checkerboard_box_size_scale: 2.5
mono_calibration_frames: 15
stereo_calibration_frames: 15
view_resize: 2
cooldown: 20
camera0_display: 'USB camera /dev/video0 (openaicam: openaicam (usb-xhci-hcd.0-1))'
camera1_display: 'USB camera /dev/video2 (openaicam: openaicam (usb-xhci-hcd.1-1))'
